# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirddegree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bandwidth',
            field=models.IntegerField(default=0),
        ),
    ]
