# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirddegree', '0002_auto_20161231_0616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_Directories',
            new_name='ClientDirectories',
        ),
    ]
