# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirddegree', '0003_auto_20161231_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='storage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1024)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='bandwidth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10240)]),
        ),
    ]
