# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirddegree', '0004_auto_20161231_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bandwidth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10485760)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='storage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1048576)]),
        ),
    ]
